### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by sldev2** [zxch3n/PomodoroLogger#157]
I'm running Windows 10. I cloned the project with no problems (version 0.3.7), but running npm install fails. The last couple of lines in Terminal are;

npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! premature close

**Comment by zxch3n** [comment]
Did you try `yarn`?

**Comment by sldev2** [comment]
No, I'm not familiar with yarn. 

> Did you try `yarn`?

I just tried it. (Never heard of it, before.)  The installation of yarn seemed to proceed just fine, but afterwards calling: 
       >yarn install
failed.

Could you please post idiot instructions for use of yarn?

**Comment by zxch3n** [comment]
What was the error message after `yarn install`? And what is your node.js version? Try to use nodejs with version at least v10.13.0

**Comment by zxch3n** [comment]
- It requires Visual Studio because this project has dependencies that are depend on it, for example `active-win`. 
- `dist` directory is created after build. `prebuild` should not fail if the folder is missing. It failed because `rd` removes empty directories in MS-DOS. To delete directories with files or directories within them, you must use the `deltree` command. For simplicity, you can use something like git bash which provides a BASH emulation.
