### ISSUE TITLE
Error in counting of the real time

### ISSUE THREAD

**Issue by loviuz** [zxch3n/PomodoroLogger#202]
**Describe the bug**

When running the application the counter starts from 12 seconds and it stops immediately after, saying me I have finished focusing. After 2 seconds it say me I have finished break.
 with ```yarn start``` I get an error

**To Reproduce**
```yarn start```

After a while it appears this error on the console:

```TS2322: Type 'Timer' is not assignable to type 'number'```

**Expected behavior**
Counter should count 25 minutes as configured, not 12 seconds. I have not edited default times, I have tried with the default settings.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/1647128/129951957-df797e3c-5868-4d2e-914c-b1ded72bf1ec.png)

**Desktop (please complete the following information):**
Ubuntu 20.04

Tried with node 14 and node 16.

**Additional context**
Same error with 0.5.3 release and master branch.

**Comment by zxch3n** [comment]
Thanks for the report. You can use the app download from [release page](https://github.com/zxch3n/PomodoroLogger/releases). `yarn start` is for development purpose, so the focus/break duration is shrunk 120x as you can see from https://github.com/zxch3n/PomodoroLogger/blob/17fe6f150ac0c98f8172a58716272bbc25bcab11/src/config.ts#L73

The error in the screenshot is a typescript type error, because `setInterval` has different return type between nodeJS env and web env. It should not affect the app's functionality. I will fix it in the next commit.

**Comment by loviuz** [comment]
Sorry, I confirm that with release it works!
